<?php

/*
 * This file is part of Respect/Validation.
 *
 * (c) Alexandre Gomes Gaigalas <alexandre@gaigalas.net>
 *
 * For the full copyright and license information, please view the "LICENSE.md"
 * file that was distributed with this source code.
 */

namespace Respect\Validation\Rules;

use stdClass;

/**
 * @group  rule
 * @covers \Respect\Validation\Rules\Name
 */
class NameTest extends RuleTestCase
{
    public function providerForValidInput()
    {
        $rule = new Name();

        return [
            [$rule, '\'s Gravenhage'],
            [$rule, 'Achadh a\' Chuirn'],
            [$rule, 'Ak-Mechet'],
            [$rule, 'Ali-Agok'],
            [$rule, 'Am Blàran Odhar'],
            [$rule, 'Amoy'],
            [$rule, 'Aqmeçit'],
            [$rule, 'Aqşeyh'],
            [$rule, 'Astraxan-Bazar'],
            [$rule, 'Azaña'],
            [$rule, 'Aşağı Ağcakənd'],
            [$rule, 'Aşağı Kikineiz'],
            [$rule, 'Aşağı Otuz'],
            [$rule, 'Bacatá'],
            [$rule, 'Barmen-Elberfeld'],
            [$rule, 'Bayona de Tajuña'],
            [$rule, 'Bazarçıq'],
            [$rule, 'Baťovany'],
            [$rule, 'Behdesīr'],
            [$rule, 'Bekdaş'],
            [$rule, 'Bendigo\'s Creek'],
            [$rule, 'Besztercebánya'],
            [$rule, 'Beyləqan'],
            [$rule, 'Biała'],
            [$rule, 'Biała'],
            [$rule, 'Biała'],
            [$rule, 'Biały Bór'],
            [$rule, 'Biləsuvar'],
            [$rule, 'Biruința'],
            [$rule, 'Birži'],
            [$rule, 'Blackman\'s Flat'],
            [$rule, 'Bokovo-Antratsyt'],
            [$rule, 'Bosanska Gradiška'],
            [$rule, 'Bucureșci'],
            [$rule, 'Bötzow'],
            [$rule, 'Büyük Onlar'],
            [$rule, 'Błaszkowice'],
            [$rule, 'Cadȝow'],
            [$rule, 'Canköy'],
            [$rule, 'Ch\'ing-ni-wa'],
            [$rule, 'Chang\'an'],
            [$rule, 'Chișcăreni'],
            [$rule, 'Chorzów'],
            [$rule, 'Chörük-Qamarli'],
            [$rule, 'ch\'átlich'],
            [$rule, 'Cittanova d\'Istria'],
            [$rule, 'Colomb-Béchar'],
            [$rule, 'Curçı'],
            [$rule, 'd\'Istria'],
            [$rule, 'Dolossı'],
            [$rule, 'Duingji-hyeon'],
            [$rule, 'Duoliebaičiai'],
            [$rule, 'Duvannı'],
            [$rule, 'Dzierzgoń'],
            [$rule, 'Dún Laoghaire'],
            [$rule, 'Dünaburg'],
            [$rule, 'Dęblin'],
            [$rule, 'Dəvəçi'],
            [$rule, 'Eski Qırım'],
            [$rule, 'Florianów'],
            [$rule, 'Fort Pontchartrain du Détroit'],
            [$rule, 'Fort Rouillé'],
            [$rule, 'Fort-Foureau'],
            [$rule, 'Frývaldov'],
            [$rule, 'Fuchū'],
            [$rule, 'Fünfkirchen'],
            [$rule, 'Fürstenberg'],
            [$rule, 'Gamble\'s Mill'],
            [$rule, 'Gdańsk'],
            [$rule, 'Ghindești'],
            [$rule, 'Gross-Born'],
            [$rule, 'Guşgy'],
            [$rule, 'Gyzyl-arbat'],
            [$rule, 'Géryville'],
            [$rule, 'Głogów'],
            [$rule, 'Gəncə'],
            [$rule, 'Hamônia'],
            [$rule, 'Hens and Chicken\'s Harbour'],
            [$rule, 'Hilton\'s Pointe'],
            [$rule, 'Hunt\'s Mills'],
            [$rule, 'Hvoča'],
            [$rule, 'Hîncești'],
            [$rule, 'Ta-senet'],
            [$rule, 'İslâm Terek'],
            [$rule, 'İçki'],
            [$rule, 'Jabaeté'],
            [$rule, 'Jędrzychów'],
            [$rule, 'Karlo-Libknekhtovsk'],
            [$rule, 'Kostiantynivka-2'],
            [$rule, 'Kołobrzeg'],
            [$rule, 'Kurgan-Tyube'],
            [$rule, 'Kurman-Kumelĉi'],
            [$rule, 'Kōriyama'],
            [$rule, 'Lin\'an'],
            [$rule, 'Lourenço Marques'],
            [$rule, 'Léger Corner'],
            [$rule, 'Léopoldville'],
            [$rule, 'Mahé'],
            [$rule, 'Mapuça'],
            [$rule, 'Marosvásárhely'],
            [$rule, 'Mažeikiai'],
            [$rule, 'McGuire\'s Punt'],
            [$rule, 'Mieńsk'],
            [$rule, 'Moçâmedes'],
            [$rule, 'Mölndal'],
            [$rule, 'Münden'],
            [$rule, 'N\'dalatando'],
            [$rule, 'Nebit-dag'],
            [$rule, 'Neu-Herrnhut'],
            [$rule, 'Neu-Zürich'],
            [$rule, 'Noraşen'],
            [$rule, 'Nowa Wieś'],
            [$rule, 'Nowy Włodzisław'],
            [$rule, 'Nuestra Señora Santa María de los Remedios del Cabo de la Vela'],
            [$rule, 'Německé Jablonné'],
            [$rule, 'Německý Brod'],
            [$rule, 'Or Qapı'],
            [$rule, 'Ortaköy'],
            [$rule, 'Paraíba'],
            [$rule, 'Patriarca San José'],
            [$rule, 'Pašešupys'],
            [$rule, 'Perez Dasmariñas'],
            [$rule, 'Pig\'s Eye'],
            [$rule, 'Pile o\' Bones'],
            [$rule, 'Pirçivan'],
            [$rule, 'Port-Ilich'],
            [$rule, 'Pozzo Littorio d\'Arsia'],
            [$rule, 'Przemków'],
            [$rule, 'Puławy'],
            [$rule, 'Qaradağ'],
            [$rule, 'Querétaro'],
            [$rule, 'Qutqaşen'],
            [$rule, 'Qızıltaş'],
            [$rule, 'Rogoźno'],
            [$rule, 'Rusčuk'],
            [$rule, 'Saint André de Mers-el-Kébir'],
            [$rule, 'Sainte-Anne-des-Pins'],
            [$rule, 'San Bonifacio de Ibagué del valle de las Lanzas'],
            [$rule, 'San Jerónimo de Buenavista'],
            [$rule, 'Sankt Veit am Fluß'],
            [$rule, 'Santiago de León de Caracas'],
            [$rule, 'Santo António do Zaire'],
            [$rule, 'Sarre-Louis'],
            [$rule, 'Shipman\'s Corners'],
            [$rule, 'Sindian'],
            [$rule, 'Sniečkus'],
            [$rule, 'St John\'s Toun'],
            [$rule, 'Stadt des KdF-Wagens bei Fallersleben'],
            [$rule, 'Stanisławów'],
            [$rule, 'Ste. Anne\'s Point'],
            [$rule, 'Stukmaņi'],
            [$rule, 'Stučka'],
            [$rule, 'Swilling\'s Mill'],
            [$rule, 'Sá da Bandeira'],
            [$rule, 'São José da Barra do Rio Negro'],
            [$rule, 'São José del Rey'],
            [$rule, 'São Salvador'],
            [$rule, 'Sîngerei'],
            [$rule, 'Słupsk'],
            [$rule, 'Tamsui'],
            [$rule, 'Tanjungkarang-Telukbetung'],
            [$rule, 'Temesvár'],
            [$rule, 'Tenochtitlán'],
            [$rule, 'Tiszaszederkény'],
            [$rule, 'Tuléar'],
            [$rule, 'Tərtər'],
            [$rule, 'Tống Bình'],
            [$rule, 'Ura-Tyube'],
            [$rule, 'Ust-Kamennaya'],
            [$rule, 'Užice'],
            [$rule, 'Vartaşen'],
            [$rule, 'Veliki Bečkerek'],
            [$rule, 'Vila do Espírito Santo'],
            [$rule, 'Vila Nova do Espírito Santo'],
            [$rule, 'Vilkmergė'],
            [$rule, 'Villa Holguí'],
            [$rule, 'Villaviciosa de la Concepción de la Provincia de Hatunllacta'],
            [$rule, 'Vörde'],
            [$rule, 'Wanggeom-seong'],
            [$rule, 'Wankie'],
            [$rule, 'Wielka Wieś'],
            [$rule, 'Wietrzna Góra'],
            [$rule, 'Wismar-MacKenzie-Christianburg'],
            [$rule, 'Wrocisław'],
            [$rule, 'Wu\'muthkweyum'],
            [$rule, 'Włodzisław'],
            [$rule, 'Xankəndi'],
            [$rule, 'Xonaşen'],
            [$rule, 'Yangi-Bazar'],
            [$rule, 'Yañı Küçükköy'],
            [$rule, 'Yeni Şamaxı'],
            [$rule, 'Zapotlán'],
            [$rule, 'Zielona Góra'],
            [$rule, 'Zlín'],
            [$rule, 'Çeleken'],
            [$rule, 'Östra Aros'],
            [$rule, 'Łoza'],
            [$rule, 'Łódź'],
            [$rule, 'Łęg'],
            [$rule, 'Ōminatotanabu'],
            [$rule, 'Ōmiya'],
            [$rule, 'Ōta'],
            [$rule, 'Ōtsu'],
            [$rule, 'Ōtsu'],
            [$rule, 'Şəki'],
            [$rule, 'Şəmkir'],
            [$rule, 'Šilokarčema'],
            [$rule, 'Żółkiew'],
            [$rule, 'Șoldănești'],
            [$rule, 'Берестье'],
            [$rule, 'русский'],
            [$rule, 'русьскъ'],
            [$rule, 'ру́сский'],
            [$rule, 'ру́сская во́дка'],
            [$rule, 'ру́сская вы́хухоль'],
            [$rule, 'ру́сский замо́к'],
            [$rule, 'ру́сский осётр'],
            [$rule, 'ру́сский мороз'],
            [$rule, 'ру́сский «аво́сь»‎'],
            [$rule, 'ру́сский бале́т'],
            [$rule, 'ру́сский хокке́й'],
            [$rule, 'U2'],
            [$rule, 'Amém'],
            [new Name('RU'), 'чудно́'],
            [new Name('RU'), 'ру́сский'],
        ];
    }

    public function providerForInvalidInput()
    {
        $rule = new Name();

        return [
            [$rule, '• How'],
            [$rule, '😀'],
            [$rule, []],
            [$rule, function () {
            }],
            [$rule, new stdClass()],
            [$rule, null],
            [$rule, tmpfile()],
            [new Name('EN'), 'Берестье'],
        ];
    }
}
