name: Update domains

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-tld:
    name: Update domains

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ secrets.LAST_MINOR_VERSION }}

      - name: Execute bin/update-domain-toplevel
        run: bin/update-domain-toplevel

      - name: Execute bin/update-domain-suffixes
        run: bin/update-domain-suffixes

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: The Respect Panda <therespectpanda@gmail.com>
          author: The Respect Panda <therespectpanda@gmail.com>
          commit-message: Update list of domains
          title: Update list of domains
          base: ${{ secrets.LAST_MINOR_VERSION }}
          branch: "workflows/update-tld"
