name: Update currency codes

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-currency-codes:
    name: Update currency codes

    runs-on: ubuntu-latest

    steps:
      - name: Install xmlstarlet
        run: sudo apt install xmlstarlet

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ secrets.LAST_MINOR_VERSION }}

      - name: Execute script
        run: bin/update-currency-codes

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          committer: The Respect Panda <therespectpanda@gmail.com>
          author: The Respect Panda <therespectpanda@gmail.com>
          commit-message: Update list of currency codes
          title: Update list of currency codes
          base: ${{ secrets.LAST_MINOR_VERSION }}
          branch: "workflows/update-currency-codes"
