name: Update currency codes

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  update-currency-codes:
    name: Update currency codes

    runs-on: ubuntu-latest

    steps:
      - name: Install xmlstarlet
        run: sudo apt install xmlstarlet

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "2.0"

      - name: Execute script
        run: bin/update-currency-codes

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          committer: The Respect Panda <therespectpanda@gmail.com>
          author: The Respect Panda <therespectpanda@gmail.com>
          commit-message: Update list of currency codes
          title: Update list of currency codes
          base: "2.0"
          branch: "workflows/update-currency-codes"
